In [31]:
# imported pandas library to process the dataset. as pd means alias name. we can use pd instead of pandas.
import pandas as pd

In [32]:
# read salary-data csv file and stores it in a dataset variable
dataset=pd.read_csv("Salary_Data.csv")

In [33]:
#display content
dataset

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [35]:
#Extract the Yearsexperience column from dataset and stores it in the independent variable as input
independent=dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [34]:
##Extract the salary column from dataset and stores it in the dependent variable as the output
dependent=dataset[["Salary"]]
dependent

    Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [15]:
# splitting datasets into train and data sets using train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [36]:
# creates LinearRegression model and stores it in a regressor variable
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train) # trains the linearRegression model using train datas

LinearRegression()

In [38]:
# gets the weight from the model and stores in weight variable(for 1 year of experience is increase,the salary increases by this weight) 
weight=regressor.coef_
weight

array([[9360.26128619]])

In [39]:
#gets the intercept value from the model, stores it in a bias variable.it is the origin point.if 0 years experience,this bias is the salary.
bias=regressor.intercept_
bias

array([26777.3913412])

In [40]:
# predicts the test data using trained model stores it in y_pred varaibale
y_pred=regressor.predict(x_test)

In [41]:
# evaluate the model performance, calculate r2 score by comaparing test output and predicted output
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [42]:
#stores result in r_score variable
r_score

0.9740993407213511

In [43]:
# import pickle library to save the finalized model
import pickle
filename="Finalized_model_linear.sav"

In [44]:
# saves the finalized model to a file using pickle library
pickle.dump(regressor,open(filename,"wb"))

In [47]:
#loads the finalized model and stores it in a loaded_model varaible
loaded_model=pickle.load(open("Finalized_model_linear.sav","rb"))
result=loaded_model.predict([[14]]) # predict the salary for 14 years of experience and store it in a result variable

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [46]:
#display result
result

array([[157821.04934791]])